
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Shop
{ 
    /// <summary>
    /// 商店购买类型
    /// </summary>
    public enum DailyBuyType
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 免费
        /// </summary>
        Free = 1,
        /// <summary>
        /// 金币
        /// </summary>
        Gold = 2,
        /// <summary>
        /// 钻石
        /// </summary>
        Gem = 3,
        /// <summary>
        /// 广告
        /// </summary>
        Ad = 4,
        /// <summary>
        /// 不可购买
        /// </summary>
        NotBuy = 5,
    }

} 

