
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Com
{
/// <summary>
/// 物品奖励
/// </summary>
public sealed partial class ItemRewards : Luban.BeanBase
{
    public ItemRewards(ByteBuf _buf) 
    {
        ItemID = _buf.ReadInt();
        ItemCount = _buf.ReadInt();
        ItemProb = _buf.ReadInt();
    }

    public static ItemRewards DeserializeItemRewards(ByteBuf _buf)
    {
        return new Com.ItemRewards(_buf);
    }

    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int ItemID;
    /// <summary>
    /// 物品数量
    /// </summary>
    public readonly int ItemCount;
    /// <summary>
    /// 物品概率
    /// </summary>
    public readonly int ItemProb;
   
    public const int __ID__ = -394393756;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "ItemCount:" + ItemCount + ","
        + "ItemProb:" + ItemProb + ","
        + "}";
    }
}

}

