
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Com
{
/// <summary>
/// 物品奖励
/// </summary>
public sealed partial class ItemRewards : Luban.BeanBase
{
    public ItemRewards(JSONNode _buf) 
    {
        { if(!_buf["ItemID"].IsNumber) { throw new SerializationException(); }  ItemID = _buf["ItemID"]; }
        { if(!_buf["ItemCount"].IsNumber) { throw new SerializationException(); }  ItemCount = _buf["ItemCount"]; }
        { if(!_buf["ItemProb"].IsNumber) { throw new SerializationException(); }  ItemProb = _buf["ItemProb"]; }
    }

    public static ItemRewards DeserializeItemRewards(JSONNode _buf)
    {
        return new Com.ItemRewards(_buf);
    }

    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int ItemID;
    /// <summary>
    /// 物品数量
    /// </summary>
    public readonly int ItemCount;
    /// <summary>
    /// 物品概率
    /// </summary>
    public readonly int ItemProb;
   
    public const int __ID__ = -394393756;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "ItemCount:" + ItemCount + ","
        + "ItemProb:" + ItemProb + ","
        + "}";
    }
}

}

