
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Task
{ 
    /// <summary>
    /// 任务分类
    /// </summary>
    public enum Category
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 日常
        /// </summary>
        Daily = 1,
        /// <summary>
        /// 周常
        /// </summary>
        Week = 2,
        /// <summary>
        /// 7日挑战
        /// </summary>
        DayChallenge = 3,
    }

} 

