
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Task
{ 
    /// <summary>
    /// 任务签到类型
    /// </summary>
    public enum CheckinType
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 日签到
        /// </summary>
        Daily = 1,
        /// <summary>
        /// 月签到
        /// </summary>
        Month = 2,
        /// <summary>
        /// 7日签到
        /// </summary>
        DayCheckin = 3,
    }

} 

