
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Bag
{ 
    /// <summary>
    /// 道具材料类型
    /// </summary>
    public enum ItemMateralType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 武器图纸
        /// </summary>
        WeaponPic = 1,
        /// <summary>
        /// 装备图纸
        /// </summary>
        GearPic = 2,
        /// <summary>
        /// 天赋材料
        /// </summary>
        TalentBook = 3,
        /// <summary>
        /// 头像框
        /// </summary>
        AvatarFrame = 4,
    }

} 

