
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Bag
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum ItemGoodsType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 角色货币
        /// </summary>
        Values = 1,
        /// <summary>
        /// 材料
        /// </summary>
        Stuff = 2,
        /// <summary>
        /// 宝箱
        /// </summary>
        Chest = 4,
        /// <summary>
        /// 装备
        /// </summary>
        GearPic = 8,
        /// <summary>
        /// 武器碎片
        /// </summary>
        WeaponPic = 16,
    }

} 

