
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Weapon
{ 
    public enum PrayType
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 武器祈愿
        /// </summary>
        Weapon = 1,
        /// <summary>
        /// 钻石祈愿
        /// </summary>
        Gem = 2,
        /// <summary>
        /// 武器祈愿抽取
        /// </summary>
        WeaponExtract = 3,
    }

} 

