
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Weapon
{ 
    public enum Quality
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 优秀
        /// </summary>
        Good = 1,
        /// <summary>
        /// 精良
        /// </summary>
        Perfect = 2,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 3,
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 4,
    }

} 

