
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CfLocalization : Luban.BeanBase
{
    public CfLocalization(JSONNode _buf) 
    {
        { if(!_buf["LanguageID"].IsNumber) { throw new SerializationException(); }  LanguageID = _buf["LanguageID"]; }
        { if(!_buf["CN"].IsString) { throw new SerializationException(); }  CN = _buf["CN"]; }
        { if(!_buf["EN"].IsString) { throw new SerializationException(); }  EN = _buf["EN"]; }
    }

    public static CfLocalization DeserializeCfLocalization(JSONNode _buf)
    {
        return new CfLocalization(_buf);
    }

    /// <summary>
    /// 语言ID
    /// </summary>
    public readonly int LanguageID;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string CN;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string EN;
   
    public const int __ID__ = -22710596;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "LanguageID:" + LanguageID + ","
        + "CN:" + CN + ","
        + "EN:" + EN + ","
        + "}";
    }
}

}

