
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CfLocalization : Luban.BeanBase
{
    public CfLocalization(ByteBuf _buf) 
    {
        LanguageID = _buf.ReadInt();
        CN = _buf.ReadString();
        EN = _buf.ReadString();
    }

    public static CfLocalization DeserializeCfLocalization(ByteBuf _buf)
    {
        return new CfLocalization(_buf);
    }

    /// <summary>
    /// 语言ID
    /// </summary>
    public readonly int LanguageID;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string CN;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string EN;
   
    public const int __ID__ = -22710596;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "LanguageID:" + LanguageID + ","
        + "CN:" + CN + ","
        + "EN:" + EN + ","
        + "}";
    }
}

}

