
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Battle.TBGLConst TBGLConst {get; }
    public Battle.TBWeapon TBWeapon {get; }
    public Battle.TBWeaponGrade TBWeaponGrade {get; }
    public Battle.TBWeaponQuality TBWeaponQuality {get; }
    public Battle.TBWeaponAttribute TBWeaponAttribute {get; }
    public Battle.TBMonster TBMonster {get; }
    public Battle.TBRogueSkill TBRogueSkill {get; }
    public Battle.TBChapterLevel TBChapterLevel {get; }
    public Battle.TBGoods TBGoods {get; }
    public Battle.TBTalent TBTalent {get; }
    public Battle.TBLevel TBLevel {get; }
    public Battle.TBBattleLevel TBBattleLevel {get; }
    public Battle.TBTaskType TBTaskType {get; }
    public Battle.TBTaskCheckin TBTaskCheckin {get; }
    public Battle.TBTaskList TBTaskList {get; }
    public Battle.TBTaskScore TBTaskScore {get; }
    public Battle.TBTaskAchievement TBTaskAchievement {get; }
    public Battle.TBTaskChallenge TBTaskChallenge {get; }
    public Battle.TBShopGem TBShopGem {get; }
    public Battle.TBShopDaily TBShopDaily {get; }
    public Battle.TBShopMember TBShopMember {get; }
    public Battle.TBShopChapter TBShopChapter {get; }
    public Battle.TBShopFirstRecharge TBShopFirstRecharge {get; }
    public Battle.TBFeatureUnlock TBFeatureUnlock {get; }
    public Battle.TBShopGold TBShopGold {get; }
    public Battle.TBCellUnlock TBCellUnlock {get; }
    public Battle.TBWeaponPray TBWeaponPray {get; }
    public Battle.TBWeaponPrayEnsure TBWeaponPrayEnsure {get; }
    public Battle.TBTutorial TBTutorial {get; }
    public TBLocalization TBLocalization {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TBGLConst = new Battle.TBGLConst(loader("battle_tbglconst"));
        TBWeapon = new Battle.TBWeapon(loader("battle_tbweapon"));
        TBWeaponGrade = new Battle.TBWeaponGrade(loader("battle_tbweapongrade"));
        TBWeaponQuality = new Battle.TBWeaponQuality(loader("battle_tbweaponquality"));
        TBWeaponAttribute = new Battle.TBWeaponAttribute(loader("battle_tbweaponattribute"));
        TBMonster = new Battle.TBMonster(loader("battle_tbmonster"));
        TBRogueSkill = new Battle.TBRogueSkill(loader("battle_tbrogueskill"));
        TBChapterLevel = new Battle.TBChapterLevel(loader("battle_tbchapterlevel"));
        TBGoods = new Battle.TBGoods(loader("battle_tbgoods"));
        TBTalent = new Battle.TBTalent(loader("battle_tbtalent"));
        TBLevel = new Battle.TBLevel(loader("battle_tblevel"));
        TBBattleLevel = new Battle.TBBattleLevel(loader("battle_tbbattlelevel"));
        TBTaskType = new Battle.TBTaskType(loader("battle_tbtasktype"));
        TBTaskCheckin = new Battle.TBTaskCheckin(loader("battle_tbtaskcheckin"));
        TBTaskList = new Battle.TBTaskList(loader("battle_tbtasklist"));
        TBTaskScore = new Battle.TBTaskScore(loader("battle_tbtaskscore"));
        TBTaskAchievement = new Battle.TBTaskAchievement(loader("battle_tbtaskachievement"));
        TBTaskChallenge = new Battle.TBTaskChallenge(loader("battle_tbtaskchallenge"));
        TBShopGem = new Battle.TBShopGem(loader("battle_tbshopgem"));
        TBShopDaily = new Battle.TBShopDaily(loader("battle_tbshopdaily"));
        TBShopMember = new Battle.TBShopMember(loader("battle_tbshopmember"));
        TBShopChapter = new Battle.TBShopChapter(loader("battle_tbshopchapter"));
        TBShopFirstRecharge = new Battle.TBShopFirstRecharge(loader("battle_tbshopfirstrecharge"));
        TBFeatureUnlock = new Battle.TBFeatureUnlock(loader("battle_tbfeatureunlock"));
        TBShopGold = new Battle.TBShopGold(loader("battle_tbshopgold"));
        TBCellUnlock = new Battle.TBCellUnlock(loader("battle_tbcellunlock"));
        TBWeaponPray = new Battle.TBWeaponPray(loader("battle_tbweaponpray"));
        TBWeaponPrayEnsure = new Battle.TBWeaponPrayEnsure(loader("battle_tbweaponprayensure"));
        TBTutorial = new Battle.TBTutorial(loader("battle_tbtutorial"));
        TBLocalization = new TBLocalization(loader("tblocalization"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TBGLConst.ResolveRef(this);
        TBWeapon.ResolveRef(this);
        TBWeaponGrade.ResolveRef(this);
        TBWeaponQuality.ResolveRef(this);
        TBWeaponAttribute.ResolveRef(this);
        TBMonster.ResolveRef(this);
        TBRogueSkill.ResolveRef(this);
        TBChapterLevel.ResolveRef(this);
        TBGoods.ResolveRef(this);
        TBTalent.ResolveRef(this);
        TBLevel.ResolveRef(this);
        TBBattleLevel.ResolveRef(this);
        TBTaskType.ResolveRef(this);
        TBTaskCheckin.ResolveRef(this);
        TBTaskList.ResolveRef(this);
        TBTaskScore.ResolveRef(this);
        TBTaskAchievement.ResolveRef(this);
        TBTaskChallenge.ResolveRef(this);
        TBShopGem.ResolveRef(this);
        TBShopDaily.ResolveRef(this);
        TBShopMember.ResolveRef(this);
        TBShopChapter.ResolveRef(this);
        TBShopFirstRecharge.ResolveRef(this);
        TBFeatureUnlock.ResolveRef(this);
        TBShopGold.ResolveRef(this);
        TBCellUnlock.ResolveRef(this);
        TBWeaponPray.ResolveRef(this);
        TBWeaponPrayEnsure.ResolveRef(this);
        TBTutorial.ResolveRef(this);
        TBLocalization.ResolveRef(this);
    }
}

}
