
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBLocalization
{
    private readonly System.Collections.Generic.Dictionary<int, CfLocalization> _dataMap;
    private readonly System.Collections.Generic.List<CfLocalization> _dataList;
    
    public TBLocalization(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CfLocalization>();
        _dataList = new System.Collections.Generic.List<CfLocalization>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CfLocalization _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CfLocalization.DeserializeCfLocalization(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.LanguageID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CfLocalization> DataMap => _dataMap;
    public System.Collections.Generic.List<CfLocalization> DataList => _dataList;

    public CfLocalization GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CfLocalization Get(int key) => _dataMap[key];
    public CfLocalization this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

