
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TBTemp
{
    private readonly System.Collections.Generic.Dictionary<int, CfTemp> _dataMap;
    private readonly System.Collections.Generic.List<CfTemp> _dataList;
    
    public TBTemp(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CfTemp>();
        _dataList = new System.Collections.Generic.List<CfTemp>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CfTemp _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CfTemp.DeserializeCfTemp(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CfTemp> DataMap => _dataMap;
    public System.Collections.Generic.List<CfTemp> DataList => _dataList;

    public CfTemp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CfTemp Get(int key) => _dataMap[key];
    public CfTemp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

