
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Common
{ 
    /// <summary>
    /// 功能解锁类型
    /// </summary>
    public enum FuctionUnlock
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 天赋功能
        /// </summary>
        Talent = 1,
        /// <summary>
        /// 武器功能
        /// </summary>
        Weapon = 2,
        /// <summary>
        /// 武器祈愿
        /// </summary>
        WeaponLottery = 3,
        /// <summary>
        /// 首冲
        /// </summary>
        FirstCharge = 4,
        /// <summary>
        /// 每日挑战
        /// </summary>
        Challenge = 5,
        /// <summary>
        /// 开服七日活动
        /// </summary>
        SevenEvent = 6,
        /// <summary>
        /// 开服七日签到
        /// </summary>
        SevenSign = 7,
        /// <summary>
        /// 扫荡功能
        /// </summary>
        SweepFunction = 8,
        /// <summary>
        /// 排行榜
        /// </summary>
        Ranking = 9,
        /// <summary>
        /// 钻石祈愿
        /// </summary>
        DiamondLottery = 10,
        /// <summary>
        /// 武器栏第7格
        /// </summary>
        WeaponSlot7 = 11,
        /// <summary>
        /// 武器栏第8格
        /// </summary>
        WeaponSlot8 = 12,
        /// <summary>
        /// 武器栏第9格
        /// </summary>
        WeaponSlot9 = 13,
    }

} 

