
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Common
{ 
    /// <summary>
    /// 通用目标页面
    /// </summary>
    public enum TargetPage
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 首页
        /// </summary>
        Home = 1,
        /// <summary>
        /// 商店
        /// </summary>
        Shop = 2,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 3,
        /// <summary>
        /// 天赋
        /// </summary>
        Talent = 4,
        /// <summary>
        /// 体力购买
        /// </summary>
        FoodPur = 5,
        /// <summary>
        /// 武器祈愿
        /// </summary>
        WeaponLottery = 6,
        /// <summary>
        /// 排行榜
        /// </summary>
        Rank = 7,
        /// <summary>
        /// 活动
        /// </summary>
        Event = 8,
    }

} 

