
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 怪物攻击类型
    /// </summary>
    public enum AtkRange
    {
        /// <summary>
        /// 近战
        /// </summary>
        Melee = 0,
        /// <summary>
        /// 远程
        /// </summary>
        Range = 1,
    }

} 

