
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 网格型号
    /// </summary>
    public enum CellType
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 1格
        /// </summary>
        One = 1,
        /// <summary>
        /// 2格
        /// </summary>
        Two = 2,
        /// <summary>
        /// 3格
        /// </summary>
        Three = 3,
        /// <summary>
        /// 4格
        /// </summary>
        Four = 4,
        /// <summary>
        /// 小L格
        /// </summary>
        SmallL = 5,
        /// <summary>
        /// T格
        /// </summary>
        T = 6,
        /// <summary>
        /// L格
        /// </summary>
        L = 7,
        /// <summary>
        /// Z格
        /// </summary>
        Z = 8,
    }

} 

