
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfBattleLevel : Luban.BeanBase
{
    public CfBattleLevel(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["ChapterId"].IsNumber) { throw new SerializationException(); }  ChapterId = _buf["ChapterId"]; }
        { if(!_buf["ChapterName"].IsNumber) { throw new SerializationException(); }  ChapterName = _buf["ChapterName"]; }
        { if(!_buf["LevelId"].IsNumber) { throw new SerializationException(); }  LevelId = _buf["LevelId"]; }
        { if(!_buf["UpgradeExp"].IsNumber) { throw new SerializationException(); }  UpgradeExp = _buf["UpgradeExp"]; }
        { if(!_buf["UpgradeExpAmount"].IsNumber) { throw new SerializationException(); }  UpgradeExpAmount = _buf["UpgradeExpAmount"]; }
    }

    public static CfBattleLevel DeserializeCfBattleLevel(JSONNode _buf)
    {
        return new Battle.CfBattleLevel(_buf);
    }

    /// <summary>
    /// 条目
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 章节id
    /// </summary>
    public readonly int ChapterId;
    /// <summary>
    /// 章节名称
    /// </summary>
    public readonly int ChapterName;
    /// <summary>
    /// 战斗等级
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 关卡经验
    /// </summary>
    public readonly int UpgradeExp;
    /// <summary>
    /// 总经验
    /// </summary>
    public readonly int UpgradeExpAmount;
   
    public const int __ID__ = 705718931;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ChapterId:" + ChapterId + ","
        + "ChapterName:" + ChapterName + ","
        + "LevelId:" + LevelId + ","
        + "UpgradeExp:" + UpgradeExp + ","
        + "UpgradeExpAmount:" + UpgradeExpAmount + ","
        + "}";
    }
}

}

