
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfBattleLevel : Luban.BeanBase
{
    public CfBattleLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ChapterId = _buf.ReadInt();
        ChapterName = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        UpgradeExp = _buf.ReadInt();
        UpgradeExpAmount = _buf.ReadInt();
    }

    public static CfBattleLevel DeserializeCfBattleLevel(ByteBuf _buf)
    {
        return new Battle.CfBattleLevel(_buf);
    }

    /// <summary>
    /// 条目
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 章节id
    /// </summary>
    public readonly int ChapterId;
    /// <summary>
    /// 章节名称
    /// </summary>
    public readonly int ChapterName;
    /// <summary>
    /// 战斗等级
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 关卡经验
    /// </summary>
    public readonly int UpgradeExp;
    /// <summary>
    /// 总经验
    /// </summary>
    public readonly int UpgradeExpAmount;
   
    public const int __ID__ = 705718931;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ChapterId:" + ChapterId + ","
        + "ChapterName:" + ChapterName + ","
        + "LevelId:" + LevelId + ","
        + "UpgradeExp:" + UpgradeExp + ","
        + "UpgradeExpAmount:" + UpgradeExpAmount + ","
        + "}";
    }
}

}

