
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfCellUnlock : Luban.BeanBase
{
    public CfCellUnlock(ByteBuf _buf) 
    {
        FunctionId = _buf.ReadInt();
        FuctionText = _buf.ReadInt();
        StageID = _buf.ReadInt();
    }

    public static CfCellUnlock DeserializeCfCellUnlock(ByteBuf _buf)
    {
        return new Battle.CfCellUnlock(_buf);
    }

    /// <summary>
    /// 功能ID
    /// </summary>
    public readonly int FunctionId;
    /// <summary>
    /// 解锁弹出文本
    /// </summary>
    public readonly int FuctionText;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int StageID;
   
    public const int __ID__ = -1524355713;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "FunctionId:" + FunctionId + ","
        + "FuctionText:" + FuctionText + ","
        + "StageID:" + StageID + ","
        + "}";
    }
}

}

