
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfFeatureUnlock : Luban.BeanBase
{
    public CfFeatureUnlock(ByteBuf _buf) 
    {
        FunctionId = _buf.ReadInt();
        IsDisplay = _buf.ReadBool();
        FuctionIcon = _buf.ReadString();
        FuctionName = _buf.ReadInt();
        StageID = _buf.ReadInt();
        UnlockNotice = _buf.ReadInt();
    }

    public static CfFeatureUnlock DeserializeCfFeatureUnlock(ByteBuf _buf)
    {
        return new Battle.CfFeatureUnlock(_buf);
    }

    /// <summary>
    /// 功能ID
    /// </summary>
    public readonly int FunctionId;
    /// <summary>
    /// 是否弹出
    /// </summary>
    public readonly bool IsDisplay;
    /// <summary>
    /// 功能图标
    /// </summary>
    public readonly string FuctionIcon;
    /// <summary>
    /// 功能名称
    /// </summary>
    public readonly int FuctionName;
    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int StageID;
    /// <summary>
    /// 解锁提示
    /// </summary>
    public readonly int UnlockNotice;
   
    public const int __ID__ = 1058108673;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "FunctionId:" + FunctionId + ","
        + "IsDisplay:" + IsDisplay + ","
        + "FuctionIcon:" + FuctionIcon + ","
        + "FuctionName:" + FuctionName + ","
        + "StageID:" + StageID + ","
        + "UnlockNotice:" + UnlockNotice + ","
        + "}";
    }
}

}

