
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfGoods : Luban.BeanBase
{
    public CfGoods(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemName = _buf.ReadInt();
        ItemType = (Bag.ItemGoodsType)_buf.ReadInt();
        IsInPackage = _buf.ReadBool();
        ItemMaterialType = (Bag.ItemMateralType)_buf.ReadInt();
        ItemParams = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemRewards = new System.Collections.Generic.List<Com.ItemRewards>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Com.ItemRewards _e0;  _e0 = Com.ItemRewards.DeserializeItemRewards(_buf); ItemRewards.Add(_e0);}}
        ItemDescription = _buf.ReadInt();
        ItemQuality = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ItemCollect = new System.Collections.Generic.List<Common.TargetPage>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Common.TargetPage _e0;  _e0 = (Common.TargetPage)_buf.ReadInt(); ItemCollect.Add(_e0);}}
    }

    public static CfGoods DeserializeCfGoods(ByteBuf _buf)
    {
        return new Battle.CfGoods(_buf);
    }

    /// <summary>
    /// 道具等级ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly int ItemName;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly Bag.ItemGoodsType ItemType;
    /// <summary>
    /// 是否在包裹
    /// </summary>
    public readonly bool IsInPackage;
    /// <summary>
    /// 材料类型
    /// </summary>
    public readonly Bag.ItemMateralType ItemMaterialType;
    /// <summary>
    /// 道具参数:材料(1随机) 宝箱:(1随机 2自选)  武器碎片:(武器id)
    /// </summary>
    public readonly int ItemParams;
    /// <summary>
    /// 道具奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Com.ItemRewards> ItemRewards;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly int ItemDescription;
    /// <summary>
    /// 道具品质
    /// </summary>
    public readonly int ItemQuality;
    /// <summary>
    /// 来源
    /// </summary>
    public readonly System.Collections.Generic.List<Common.TargetPage> ItemCollect;
   
    public const int __ID__ = 1372679549;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ItemRewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ItemName:" + ItemName + ","
        + "ItemType:" + ItemType + ","
        + "IsInPackage:" + IsInPackage + ","
        + "ItemMaterialType:" + ItemMaterialType + ","
        + "ItemParams:" + ItemParams + ","
        + "ItemRewards:" + Luban.StringUtil.CollectionToString(ItemRewards) + ","
        + "ItemDescription:" + ItemDescription + ","
        + "ItemQuality:" + ItemQuality + ","
        + "ItemCollect:" + Luban.StringUtil.CollectionToString(ItemCollect) + ","
        + "}";
    }
}

}

