
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfLevel : Luban.BeanBase
{
    public CfLevel(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["UpgradeExp"].IsNumber) { throw new SerializationException(); }  UpgradeExp = _buf["UpgradeExp"]; }
        { if(!_buf["TotalExp"].IsNumber) { throw new SerializationException(); }  TotalExp = _buf["TotalExp"]; }
    }

    public static CfLevel DeserializeCfLevel(JSONNode _buf)
    {
        return new Battle.CfLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级经验
    /// </summary>
    public readonly int UpgradeExp;
    /// <summary>
    /// 升级总经验
    /// </summary>
    public readonly int TotalExp;
   
    public const int __ID__ = 1377005995;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UpgradeExp:" + UpgradeExp + ","
        + "TotalExp:" + TotalExp + ","
        + "}";
    }
}

}

