
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfLevel : Luban.BeanBase
{
    public CfLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UpgradeExp = _buf.ReadInt();
        TotalExp = _buf.ReadInt();
    }

    public static CfLevel DeserializeCfLevel(ByteBuf _buf)
    {
        return new Battle.CfLevel(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 升级经验
    /// </summary>
    public readonly int UpgradeExp;
    /// <summary>
    /// 升级总经验
    /// </summary>
    public readonly int TotalExp;
   
    public const int __ID__ = 1377005995;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UpgradeExp:" + UpgradeExp + ","
        + "TotalExp:" + TotalExp + ","
        + "}";
    }
}

}

