
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfMonster : Luban.BeanBase
{
    public CfMonster(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["AssetPath"].IsString) { throw new SerializationException(); }  AssetPath = _buf["AssetPath"]; }
        { if(!_buf["Name"].IsNumber) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["BulletAsset"].IsString) { throw new SerializationException(); }  BulletAsset = _buf["BulletAsset"]; }
        { var __json0 = _buf["DefaultBuffList"]; if(!__json0.IsArray) { throw new SerializationException(); } DefaultBuffList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DefaultBuffList.Add(__v0); }   }
        { if(!_buf["IsBoss"].IsBoolean) { throw new SerializationException(); }  IsBoss = _buf["IsBoss"]; }
        { if(!_buf["MonsterExp"].IsNumber) { throw new SerializationException(); }  MonsterExp = _buf["MonsterExp"]; }
        { if(!_buf["AtkRange"].IsNumber) { throw new SerializationException(); }  AtkRange = (Battle.AtkRange)_buf["AtkRange"].AsInt; }
        { if(!_buf["AP"].IsNumber) { throw new SerializationException(); }  AP = _buf["AP"]; }
        { if(!_buf["CT"].IsNumber) { throw new SerializationException(); }  CT = _buf["CT"]; }
        { if(!_buf["Hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["Hp"]; }
        { if(!_buf["Rng"].IsNumber) { throw new SerializationException(); }  Rng = _buf["Rng"]; }
        { if(!_buf["Shld"].IsNumber) { throw new SerializationException(); }  Shld = _buf["Shld"]; }
        { if(!_buf["MSpd"].IsNumber) { throw new SerializationException(); }  MSpd = _buf["MSpd"]; }
    }

    public static CfMonster DeserializeCfMonster(JSONNode _buf)
    {
        return new Battle.CfMonster(_buf);
    }

    /// <summary>
    /// 怪物id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// 怪物名称
    /// </summary>
    public readonly int Name;
    /// <summary>
    /// 子弹资源
    /// </summary>
    public readonly string BulletAsset;
    /// <summary>
    /// 登场默认buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> DefaultBuffList;
    /// <summary>
    /// 是否是BOSS
    /// </summary>
    public readonly bool IsBoss;
    /// <summary>
    /// 怪物经验
    /// </summary>
    public readonly int MonsterExp;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly Battle.AtkRange AtkRange;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float AP;
    /// <summary>
    /// 冷却时间(s)
    /// </summary>
    public readonly float CT;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 射程
    /// </summary>
    public readonly float Rng;
    /// <summary>
    /// 护盾
    /// </summary>
    public readonly float Shld;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MSpd;
   
    public const int __ID__ = 1619669057;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "AssetPath:" + AssetPath + ","
        + "Name:" + Name + ","
        + "BulletAsset:" + BulletAsset + ","
        + "DefaultBuffList:" + Luban.StringUtil.CollectionToString(DefaultBuffList) + ","
        + "IsBoss:" + IsBoss + ","
        + "MonsterExp:" + MonsterExp + ","
        + "AtkRange:" + AtkRange + ","
        + "AP:" + AP + ","
        + "CT:" + CT + ","
        + "Hp:" + Hp + ","
        + "Rng:" + Rng + ","
        + "Shld:" + Shld + ","
        + "MSpd:" + MSpd + ","
        + "}";
    }
}

}

