
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfMonster : Luban.BeanBase
{
    public CfMonster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AssetPath = _buf.ReadString();
        Name = _buf.ReadInt();
        BulletAsset = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DefaultBuffList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DefaultBuffList.Add(_e0);}}
        IsBoss = _buf.ReadBool();
        MonsterExp = _buf.ReadInt();
        AtkRange = (Battle.AtkRange)_buf.ReadInt();
        AP = _buf.ReadFloat();
        CT = _buf.ReadFloat();
        Hp = _buf.ReadFloat();
        Rng = _buf.ReadFloat();
        Shld = _buf.ReadFloat();
        MSpd = _buf.ReadFloat();
    }

    public static CfMonster DeserializeCfMonster(ByteBuf _buf)
    {
        return new Battle.CfMonster(_buf);
    }

    /// <summary>
    /// 怪物id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// 怪物名称
    /// </summary>
    public readonly int Name;
    /// <summary>
    /// 子弹资源
    /// </summary>
    public readonly string BulletAsset;
    /// <summary>
    /// 登场默认buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> DefaultBuffList;
    /// <summary>
    /// 是否是BOSS
    /// </summary>
    public readonly bool IsBoss;
    /// <summary>
    /// 怪物经验
    /// </summary>
    public readonly int MonsterExp;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly Battle.AtkRange AtkRange;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float AP;
    /// <summary>
    /// 冷却时间(s)
    /// </summary>
    public readonly float CT;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 射程
    /// </summary>
    public readonly float Rng;
    /// <summary>
    /// 护盾
    /// </summary>
    public readonly float Shld;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly float MSpd;
   
    public const int __ID__ = 1619669057;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "AssetPath:" + AssetPath + ","
        + "Name:" + Name + ","
        + "BulletAsset:" + BulletAsset + ","
        + "DefaultBuffList:" + Luban.StringUtil.CollectionToString(DefaultBuffList) + ","
        + "IsBoss:" + IsBoss + ","
        + "MonsterExp:" + MonsterExp + ","
        + "AtkRange:" + AtkRange + ","
        + "AP:" + AP + ","
        + "CT:" + CT + ","
        + "Hp:" + Hp + ","
        + "Rng:" + Rng + ","
        + "Shld:" + Shld + ","
        + "MSpd:" + MSpd + ","
        + "}";
    }
}

}

