
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfShopGold : Luban.BeanBase
{
    public CfShopGold(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ProductId = _buf.ReadInt();
        Price = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); Rewards.Add(_e0);}}
        BuyLimitCount = _buf.ReadInt();
    }

    public static CfShopGold DeserializeCfShopGold(ByteBuf _buf)
    {
        return new Battle.CfShopGold(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 档位
    /// </summary>
    public readonly int ProductId;
    /// <summary>
    /// 钻石价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
    /// <summary>
    /// 限购次数
    /// </summary>
    public readonly int BuyLimitCount;
   
    public const int __ID__ = -1355970321;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ProductId:" + ProductId + ","
        + "Price:" + Price + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "BuyLimitCount:" + BuyLimitCount + ","
        + "}";
    }
}

}

