
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfShopFirstRecharge : Luban.BeanBase
{
    public CfShopFirstRecharge(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ProductId = _buf.ReadInt();
        Day = _buf.ReadInt();
        Price = _buf.ReadFloat();
        DollarPrice = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); Rewards.Add(_e0);}}
    }

    public static CfShopFirstRecharge DeserializeCfShopFirstRecharge(ByteBuf _buf)
    {
        return new Battle.CfShopFirstRecharge(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 档位
    /// </summary>
    public readonly int ProductId;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 美元
    /// </summary>
    public readonly float DollarPrice;
    /// <summary>
    /// 领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
   
    public const int __ID__ = -605540920;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ProductId:" + ProductId + ","
        + "Day:" + Day + ","
        + "Price:" + Price + ","
        + "DollarPrice:" + DollarPrice + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

