
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfShopDaily : Luban.BeanBase
{
    public CfShopDaily(JSONNode _buf) 
    {
        { if(!_buf["GoodsId"].IsNumber) { throw new SerializationException(); }  GoodsId = _buf["GoodsId"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
        { if(!_buf["Times"].IsNumber) { throw new SerializationException(); }  Times = _buf["Times"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (Shop.DailyBuyType)_buf["Type"].AsInt; }
    }

    public static CfShopDaily DeserializeCfShopDaily(JSONNode _buf)
    {
        return new Battle.CfShopDaily(_buf);
    }

    /// <summary>
    /// 物品
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 次数
    /// </summary>
    public readonly int Times;
    /// <summary>
    /// 购买类型
    /// </summary>
    public readonly Shop.DailyBuyType Type;
   
    public const int __ID__ = 911402858;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GoodsId:" + GoodsId + ","
        + "Price:" + Price + ","
        + "Number:" + Number + ","
        + "Times:" + Times + ","
        + "Type:" + Type + ","
        + "}";
    }
}

}

