
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfShopGem : Luban.BeanBase
{
    public CfShopGem(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["DollarPrice"].IsNumber) { throw new SerializationException(); }  DollarPrice = _buf["DollarPrice"]; }
        { if(!_buf["Gem"].IsNumber) { throw new SerializationException(); }  Gem = _buf["Gem"]; }
        { if(!_buf["FirstGift"].IsNumber) { throw new SerializationException(); }  FirstGift = _buf["FirstGift"]; }
        { if(!_buf["FirstGiftDesc"].IsNumber) { throw new SerializationException(); }  FirstGiftDesc = _buf["FirstGiftDesc"]; }
    }

    public static CfShopGem DeserializeCfShopGem(JSONNode _buf)
    {
        return new Battle.CfShopGem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 美元价格
    /// </summary>
    public readonly float DollarPrice;
    /// <summary>
    /// 钻石
    /// </summary>
    public readonly int Gem;
    /// <summary>
    /// 首冲送
    /// </summary>
    public readonly int FirstGift;
    /// <summary>
    /// 首冲描述
    /// </summary>
    public readonly int FirstGiftDesc;
   
    public const int __ID__ = -1844856608;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Price:" + Price + ","
        + "DollarPrice:" + DollarPrice + ","
        + "Gem:" + Gem + ","
        + "FirstGift:" + FirstGift + ","
        + "FirstGiftDesc:" + FirstGiftDesc + ","
        + "}";
    }
}

}

