
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfShopMember : Luban.BeanBase
{
    public CfShopMember(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Title"].IsNumber) { throw new SerializationException(); }  Title = _buf["Title"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["DollarPrice"].IsNumber) { throw new SerializationException(); }  DollarPrice = _buf["DollarPrice"]; }
        { var __json0 = _buf["DailyRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } DailyRewards = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  DailyRewards.Add(__v0); }   }
        { var __json0 = _buf["DoubleRewards"]; if(!__json0.IsArray) { throw new SerializationException(); } DoubleRewards = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  DoubleRewards.Add(__v0); }   }
        { if(!_buf["GiftDesc"].IsNumber) { throw new SerializationException(); }  GiftDesc = _buf["GiftDesc"]; }
        { if(!_buf["Details"].IsNumber) { throw new SerializationException(); }  Details = _buf["Details"]; }
    }

    public static CfShopMember DeserializeCfShopMember(JSONNode _buf)
    {
        return new Battle.CfShopMember(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly int Title;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 美元价格
    /// </summary>
    public readonly float DollarPrice;
    /// <summary>
    /// 每日领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> DailyRewards;
    /// <summary>
    /// 双月卡领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> DoubleRewards;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly int GiftDesc;
    /// <summary>
    /// 详情
    /// </summary>
    public readonly int Details;
   
    public const int __ID__ = -1549816983;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DailyRewards) { _e?.ResolveRef(tables); }
        foreach (var _e in DoubleRewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Title:" + Title + ","
        + "Price:" + Price + ","
        + "DollarPrice:" + DollarPrice + ","
        + "DailyRewards:" + Luban.StringUtil.CollectionToString(DailyRewards) + ","
        + "DoubleRewards:" + Luban.StringUtil.CollectionToString(DoubleRewards) + ","
        + "GiftDesc:" + GiftDesc + ","
        + "Details:" + Details + ","
        + "}";
    }
}

}

