
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfShopMember : Luban.BeanBase
{
    public CfShopMember(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Title = _buf.ReadInt();
        Price = _buf.ReadFloat();
        DollarPrice = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DailyRewards = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); DailyRewards.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DoubleRewards = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); DoubleRewards.Add(_e0);}}
        GiftDesc = _buf.ReadInt();
        Details = _buf.ReadInt();
    }

    public static CfShopMember DeserializeCfShopMember(ByteBuf _buf)
    {
        return new Battle.CfShopMember(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly int Title;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 美元价格
    /// </summary>
    public readonly float DollarPrice;
    /// <summary>
    /// 每日领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> DailyRewards;
    /// <summary>
    /// 双月卡领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> DoubleRewards;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly int GiftDesc;
    /// <summary>
    /// 详情
    /// </summary>
    public readonly int Details;
   
    public const int __ID__ = -1549816983;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in DailyRewards) { _e?.ResolveRef(tables); }
        foreach (var _e in DoubleRewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Title:" + Title + ","
        + "Price:" + Price + ","
        + "DollarPrice:" + DollarPrice + ","
        + "DailyRewards:" + Luban.StringUtil.CollectionToString(DailyRewards) + ","
        + "DoubleRewards:" + Luban.StringUtil.CollectionToString(DoubleRewards) + ","
        + "GiftDesc:" + GiftDesc + ","
        + "Details:" + Details + ","
        + "}";
    }
}

}

