
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfShopFirstRecharge : Luban.BeanBase
{
    public CfShopFirstRecharge(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["ProductId"].IsNumber) { throw new SerializationException(); }  ProductId = _buf["ProductId"]; }
        { if(!_buf["Day"].IsNumber) { throw new SerializationException(); }  Day = _buf["Day"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { if(!_buf["DollarPrice"].IsNumber) { throw new SerializationException(); }  DollarPrice = _buf["DollarPrice"]; }
        { var __json0 = _buf["Rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  Rewards.Add(__v0); }   }
    }

    public static CfShopFirstRecharge DeserializeCfShopFirstRecharge(JSONNode _buf)
    {
        return new Battle.CfShopFirstRecharge(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 档位
    /// </summary>
    public readonly int ProductId;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly float Price;
    /// <summary>
    /// 美元
    /// </summary>
    public readonly float DollarPrice;
    /// <summary>
    /// 领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
   
    public const int __ID__ = -605540920;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ProductId:" + ProductId + ","
        + "Day:" + Day + ","
        + "Price:" + Price + ","
        + "DollarPrice:" + DollarPrice + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

