
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfShopGold : Luban.BeanBase
{
    public CfShopGold(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["ProductId"].IsNumber) { throw new SerializationException(); }  ProductId = _buf["ProductId"]; }
        { if(!_buf["Price"].IsNumber) { throw new SerializationException(); }  Price = _buf["Price"]; }
        { var __json0 = _buf["Rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  Rewards.Add(__v0); }   }
        { if(!_buf["BuyLimitCount"].IsNumber) { throw new SerializationException(); }  BuyLimitCount = _buf["BuyLimitCount"]; }
    }

    public static CfShopGold DeserializeCfShopGold(JSONNode _buf)
    {
        return new Battle.CfShopGold(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 档位
    /// </summary>
    public readonly int ProductId;
    /// <summary>
    /// 钻石价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
    /// <summary>
    /// 限购次数
    /// </summary>
    public readonly int BuyLimitCount;
   
    public const int __ID__ = -1355970321;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ProductId:" + ProductId + ","
        + "Price:" + Price + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "BuyLimitCount:" + BuyLimitCount + ","
        + "}";
    }
}

}

