
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfShopChapter : Luban.BeanBase
{
    public CfShopChapter(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Title = _buf.ReadInt();
        Price = _buf.ReadInt();
        DollarPrice = _buf.ReadFloat();
        OriginalDollarPrice = _buf.ReadFloat();
        OriginalPrice = _buf.ReadFloat();
        GiftDesc = _buf.ReadInt();
        DiscountDesc = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); Rewards.Add(_e0);}}
    }

    public static CfShopChapter DeserializeCfShopChapter(ByteBuf _buf)
    {
        return new Battle.CfShopChapter(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly int Title;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 美元价格
    /// </summary>
    public readonly float DollarPrice;
    /// <summary>
    /// 美元原价
    /// </summary>
    public readonly float OriginalDollarPrice;
    /// <summary>
    /// 原价
    /// </summary>
    public readonly float OriginalPrice;
    /// <summary>
    /// 礼包描述
    /// </summary>
    public readonly int GiftDesc;
    /// <summary>
    /// 折扣描述
    /// </summary>
    public readonly int DiscountDesc;
    /// <summary>
    /// 领取奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
   
    public const int __ID__ = -1009552034;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Title:" + Title + ","
        + "Price:" + Price + ","
        + "DollarPrice:" + DollarPrice + ","
        + "OriginalDollarPrice:" + OriginalDollarPrice + ","
        + "OriginalPrice:" + OriginalPrice + ","
        + "GiftDesc:" + GiftDesc + ","
        + "DiscountDesc:" + DiscountDesc + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

