
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfShopDaily : Luban.BeanBase
{
    public CfShopDaily(ByteBuf _buf) 
    {
        GoodsId = _buf.ReadInt();
        Price = _buf.ReadInt();
        Number = _buf.ReadInt();
        Times = _buf.ReadInt();
        Type = (Shop.DailyBuyType)_buf.ReadInt();
    }

    public static CfShopDaily DeserializeCfShopDaily(ByteBuf _buf)
    {
        return new Battle.CfShopDaily(_buf);
    }

    /// <summary>
    /// 物品
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Number;
    /// <summary>
    /// 次数
    /// </summary>
    public readonly int Times;
    /// <summary>
    /// 购买类型
    /// </summary>
    public readonly Shop.DailyBuyType Type;
   
    public const int __ID__ = 911402858;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GoodsId:" + GoodsId + ","
        + "Price:" + Price + ","
        + "Number:" + Number + ","
        + "Times:" + Times + ","
        + "Type:" + Type + ","
        + "}";
    }
}

}

