
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfTaskScore : Luban.BeanBase
{
    public CfTaskScore(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Category = (Task.Category)_buf.ReadInt();
        Score = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); Rewards.Add(_e0);}}
    }

    public static CfTaskScore DeserializeCfTaskScore(ByteBuf _buf)
    {
        return new Battle.CfTaskScore(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 分类
    /// </summary>
    public readonly Task.Category Category;
    /// <summary>
    /// 积分
    /// </summary>
    public readonly int Score;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
   
    public const int __ID__ = -1085002060;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Category:" + Category + ","
        + "Score:" + Score + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

