
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfTaskCheckin : Luban.BeanBase
{
    public CfTaskCheckin(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["CheckinType"].IsNumber) { throw new SerializationException(); }  CheckinType = (Task.CheckinType)_buf["CheckinType"].AsInt; }
        { if(!_buf["Daily"].IsNumber) { throw new SerializationException(); }  Daily = _buf["Daily"]; }
        { var __json0 = _buf["Rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  Rewards.Add(__v0); }   }
    }

    public static CfTaskCheckin DeserializeCfTaskCheckin(JSONNode _buf)
    {
        return new Battle.CfTaskCheckin(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 签到类型
    /// </summary>
    public readonly Task.CheckinType CheckinType;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Daily;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
   
    public const int __ID__ = -191610929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CheckinType:" + CheckinType + ","
        + "Daily:" + Daily + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

