
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfTaskChallenge : Luban.BeanBase
{
    public CfTaskChallenge(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Day = _buf.ReadInt();
        TaskType = _buf.ReadInt();
        Param = _buf.ReadInt();
        RewardScore = _buf.ReadInt();
        RewardGoods = Battle.ItemStuff.DeserializeItemStuff(_buf);
    }

    public static CfTaskChallenge DeserializeCfTaskChallenge(ByteBuf _buf)
    {
        return new Battle.CfTaskChallenge(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int TaskType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly int Param;
    /// <summary>
    /// 奖励积分
    /// </summary>
    public readonly int RewardScore;
    /// <summary>
    /// 奖励物品
    /// </summary>
    public readonly Battle.ItemStuff RewardGoods;
   
    public const int __ID__ = 1548913541;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        RewardGoods?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Day:" + Day + ","
        + "TaskType:" + TaskType + ","
        + "Param:" + Param + ","
        + "RewardScore:" + RewardScore + ","
        + "RewardGoods:" + RewardGoods + ","
        + "}";
    }
}

}

