
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfTaskChallenge : Luban.BeanBase
{
    public CfTaskChallenge(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Day"].IsNumber) { throw new SerializationException(); }  Day = _buf["Day"]; }
        { if(!_buf["TaskType"].IsNumber) { throw new SerializationException(); }  TaskType = _buf["TaskType"]; }
        { if(!_buf["Param"].IsNumber) { throw new SerializationException(); }  Param = _buf["Param"]; }
        { if(!_buf["RewardScore"].IsNumber) { throw new SerializationException(); }  RewardScore = _buf["RewardScore"]; }
        { if(!_buf["RewardGoods"].IsObject) { throw new SerializationException(); }  RewardGoods = Battle.ItemStuff.DeserializeItemStuff(_buf["RewardGoods"]);  }
    }

    public static CfTaskChallenge DeserializeCfTaskChallenge(JSONNode _buf)
    {
        return new Battle.CfTaskChallenge(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 天数
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int TaskType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly int Param;
    /// <summary>
    /// 奖励积分
    /// </summary>
    public readonly int RewardScore;
    /// <summary>
    /// 奖励物品
    /// </summary>
    public readonly Battle.ItemStuff RewardGoods;
   
    public const int __ID__ = 1548913541;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        RewardGoods?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Day:" + Day + ","
        + "TaskType:" + TaskType + ","
        + "Param:" + Param + ","
        + "RewardScore:" + RewardScore + ","
        + "RewardGoods:" + RewardGoods + ","
        + "}";
    }
}

}

