
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfTaskList : Luban.BeanBase
{
    public CfTaskList(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Category = (Task.Category)_buf.ReadInt();
        TaskType = _buf.ReadInt();
        Param = _buf.ReadInt();
        Score = _buf.ReadInt();
    }

    public static CfTaskList DeserializeCfTaskList(ByteBuf _buf)
    {
        return new Battle.CfTaskList(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 分类
    /// </summary>
    public readonly Task.Category Category;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly int TaskType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly int Param;
    /// <summary>
    /// 奖励积分
    /// </summary>
    public readonly int Score;
   
    public const int __ID__ = -1420676036;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Category:" + Category + ","
        + "TaskType:" + TaskType + ","
        + "Param:" + Param + ","
        + "Score:" + Score + ","
        + "}";
    }
}

}

