
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfTalent : Luban.BeanBase
{
    public CfTalent(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UnlockLevel = _buf.ReadInt();
        AddBlood = _buf.ReadInt();
        AddAttack = _buf.ReadInt();
        UnlockParams = Battle.ItemStuff.DeserializeItemStuff(_buf);
        IsSpecial = _buf.ReadBool();
        SkillID = _buf.ReadInt();
        AddPower = _buf.ReadInt();
    }

    public static CfTalent DeserializeCfTalent(ByteBuf _buf)
    {
        return new Battle.CfTalent(_buf);
    }

    /// <summary>
    /// 天赋ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 加血
    /// </summary>
    public readonly int AddBlood;
    /// <summary>
    /// 加攻击
    /// </summary>
    public readonly int AddAttack;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly Battle.ItemStuff UnlockParams;
    /// <summary>
    /// 是否特殊
    /// </summary>
    public readonly bool IsSpecial;
    /// <summary>
    /// 肉鸽技能ID
    /// </summary>
    public readonly int SkillID;
    /// <summary>
    /// 战力
    /// </summary>
    public readonly int AddPower;
   
    public const int __ID__ = -37445723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UnlockParams?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "AddBlood:" + AddBlood + ","
        + "AddAttack:" + AddAttack + ","
        + "UnlockParams:" + UnlockParams + ","
        + "IsSpecial:" + IsSpecial + ","
        + "SkillID:" + SkillID + ","
        + "AddPower:" + AddPower + ","
        + "}";
    }
}

}

