
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfTaskScore : Luban.BeanBase
{
    public CfTaskScore(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Category"].IsNumber) { throw new SerializationException(); }  Category = (Task.Category)_buf["Category"].AsInt; }
        { if(!_buf["Score"].IsNumber) { throw new SerializationException(); }  Score = _buf["Score"]; }
        { var __json0 = _buf["Rewards"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  Rewards.Add(__v0); }   }
    }

    public static CfTaskScore DeserializeCfTaskScore(JSONNode _buf)
    {
        return new Battle.CfTaskScore(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 分类
    /// </summary>
    public readonly Task.Category Category;
    /// <summary>
    /// 积分
    /// </summary>
    public readonly int Score;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> Rewards;
   
    public const int __ID__ = -1085002060;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Category:" + Category + ","
        + "Score:" + Score + ","
        + "Rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}

