
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfTutorial : Luban.BeanBase
{
    public CfTutorial(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AssetPath = _buf.ReadString();
    }

    public static CfTutorial DeserializeCfTutorial(ByteBuf _buf)
    {
        return new Battle.CfTutorial(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string AssetPath;
   
    public const int __ID__ = -817016873;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetPath:" + AssetPath + ","
        + "}";
    }
}

}

