
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfWeaponGrade : Luban.BeanBase
{
    public CfWeaponGrade(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemAttr = _buf.ReadInt();
        QualityID = _buf.ReadInt();
        LvlUnlockDesc = _buf.ReadInt();
        RlUnlockDesc = _buf.ReadInt();
        RlID = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MergeStuff = new System.Collections.Generic.List<Battle.ItemStuff>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Battle.ItemStuff _e0;  _e0 = Battle.ItemStuff.DeserializeItemStuff(_buf); MergeStuff.Add(_e0);}}
        Power = _buf.ReadInt();
    }

    public static CfWeaponGrade DeserializeCfWeaponGrade(ByteBuf _buf)
    {
        return new Battle.CfWeaponGrade(_buf);
    }

    /// <summary>
    /// 道具等级ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具属性
    /// </summary>
    public readonly int ItemAttr;
    /// <summary>
    /// 品质图
    /// </summary>
    public readonly int QualityID;
    /// <summary>
    /// 等级解锁描述
    /// </summary>
    public readonly int LvlUnlockDesc;
    /// <summary>
    /// 肉鸽解锁技能点
    /// </summary>
    public readonly int RlUnlockDesc;
    /// <summary>
    /// 肉鸽技能ID
    /// </summary>
    public readonly int RlID;
    /// <summary>
    /// 升级材料
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> MergeStuff;
    /// <summary>
    /// 战力
    /// </summary>
    public readonly int Power;
   
    public const int __ID__ = 1059937282;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in MergeStuff) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemAttr:" + ItemAttr + ","
        + "QualityID:" + QualityID + ","
        + "LvlUnlockDesc:" + LvlUnlockDesc + ","
        + "RlUnlockDesc:" + RlUnlockDesc + ","
        + "RlID:" + RlID + ","
        + "MergeStuff:" + Luban.StringUtil.CollectionToString(MergeStuff) + ","
        + "Power:" + Power + ","
        + "}";
    }
}

}

