
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfWeaponAttribute : Luban.BeanBase
{
    public CfWeaponAttribute(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Atk"].IsNumber) { throw new SerializationException(); }  Atk = _buf["Atk"]; }
        { if(!_buf["CD"].IsNumber) { throw new SerializationException(); }  CD = _buf["CD"]; }
        { if(!_buf["Hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["Hp"]; }
        { if(!_buf["reHp"].IsNumber) { throw new SerializationException(); }  ReHp = _buf["reHp"]; }
        { if(!_buf["Rng"].IsNumber) { throw new SerializationException(); }  Rng = _buf["Rng"]; }
        { if(!_buf["reShld"].IsNumber) { throw new SerializationException(); }  ReShld = _buf["reShld"]; }
        { if(!_buf["CritRate"].IsNumber) { throw new SerializationException(); }  CritRate = _buf["CritRate"]; }
        { if(!_buf["CritDmg"].IsNumber) { throw new SerializationException(); }  CritDmg = _buf["CritDmg"]; }
    }

    public static CfWeaponAttribute DeserializeCfWeaponAttribute(JSONNode _buf)
    {
        return new Battle.CfWeaponAttribute(_buf);
    }

    /// <summary>
    /// 属性id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Atk;
    /// <summary>
    /// 冷却时间(s)
    /// </summary>
    public readonly float CD;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 回血
    /// </summary>
    public readonly float ReHp;
    /// <summary>
    /// 射程
    /// </summary>
    public readonly float Rng;
    /// <summary>
    /// 回盾
    /// </summary>
    public readonly float ReShld;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CritRate;
    /// <summary>
    /// 暴击伤害
    /// </summary>
    public readonly float CritDmg;
   
    public const int __ID__ = 1287928135;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Atk:" + Atk + ","
        + "CD:" + CD + ","
        + "Hp:" + Hp + ","
        + "reHp:" + ReHp + ","
        + "Rng:" + Rng + ","
        + "reShld:" + ReShld + ","
        + "CritRate:" + CritRate + ","
        + "CritDmg:" + CritDmg + ","
        + "}";
    }
}

}

