
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfWeaponQuality : Luban.BeanBase
{
    public CfWeaponQuality(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemAttrPct = _buf.ReadInt();
        AssetPath = _buf.ReadString();
        BulletPath = _buf.ReadString();
    }

    public static CfWeaponQuality DeserializeCfWeaponQuality(ByteBuf _buf)
    {
        return new Battle.CfWeaponQuality(_buf);
    }

    /// <summary>
    /// 道具品阶id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具属性
    /// </summary>
    public readonly int ItemAttrPct;
    /// <summary>
    /// 预制体路径
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// 子弹资源路径
    /// </summary>
    public readonly string BulletPath;
   
    public const int __ID__ = 1063714410;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemAttrPct:" + ItemAttrPct + ","
        + "AssetPath:" + AssetPath + ","
        + "BulletPath:" + BulletPath + ","
        + "}";
    }
}

}

