
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfWeapon : Luban.BeanBase
{
    public CfWeapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemName = _buf.ReadInt();
        IsInBag = _buf.ReadBool();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AttributeList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AttributeList.Add(_e0);}}
        TargetSelectType = (Battle.TargetSelectType)_buf.ReadInt();
        AttackNum = _buf.ReadInt();
        GridX = _buf.ReadInt();
        GridY = _buf.ReadInt();
        WeaponSound = _buf.ReadString();
        CellType = (Battle.CellType)_buf.ReadInt();
        IconName = _buf.ReadString();
        ItemType = (Battle.ItemType)_buf.ReadInt();
        ElementType = (Battle.ElementType)_buf.ReadInt();
        Quality = (Battle.ItemQuality)_buf.ReadInt();
    }

    public static CfWeapon DeserializeCfWeapon(ByteBuf _buf)
    {
        return new Battle.CfWeapon(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly int ItemName;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly bool IsInBag;
    /// <summary>
    /// 属性列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> AttributeList;
    /// <summary>
    /// 攻击目标
    /// </summary>
    public readonly Battle.TargetSelectType TargetSelectType;
    /// <summary>
    /// 攻击个数
    /// </summary>
    public readonly int AttackNum;
    /// <summary>
    /// 占格长
    /// </summary>
    public readonly int GridX;
    /// <summary>
    /// 占格宽
    /// </summary>
    public readonly int GridY;
    /// <summary>
    /// 子弹音效
    /// </summary>
    public readonly string WeaponSound;
    /// <summary>
    /// 网格型号
    /// </summary>
    public readonly Battle.CellType CellType;
    /// <summary>
    /// 图形名称
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly Battle.ItemType ItemType;
    /// <summary>
    /// 元素类型
    /// </summary>
    public readonly Battle.ElementType ElementType;
    /// <summary>
    /// 品质类型
    /// </summary>
    public readonly Battle.ItemQuality Quality;
   
    public const int __ID__ = 51818709;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ItemName:" + ItemName + ","
        + "IsInBag:" + IsInBag + ","
        + "AttributeList:" + Luban.StringUtil.CollectionToString(AttributeList) + ","
        + "TargetSelectType:" + TargetSelectType + ","
        + "AttackNum:" + AttackNum + ","
        + "GridX:" + GridX + ","
        + "GridY:" + GridY + ","
        + "WeaponSound:" + WeaponSound + ","
        + "CellType:" + CellType + ","
        + "IconName:" + IconName + ","
        + "ItemType:" + ItemType + ","
        + "ElementType:" + ElementType + ","
        + "Quality:" + Quality + ","
        + "}";
    }
}

}

