
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfWeaponPrayEnsure : Luban.BeanBase
{
    public CfWeaponPrayEnsure(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (Weapon.PrayType)_buf["Type"].AsInt; }
        { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = (Weapon.Quality)_buf["Quality"].AsInt; }
        { if(!_buf["Number"].IsNumber) { throw new SerializationException(); }  Number = _buf["Number"]; }
    }

    public static CfWeaponPrayEnsure DeserializeCfWeaponPrayEnsure(JSONNode _buf)
    {
        return new Battle.CfWeaponPrayEnsure(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Weapon.PrayType Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Weapon.Quality Quality;
    /// <summary>
    /// 保底次数
    /// </summary>
    public readonly int Number;
   
    public const int __ID__ = -212419251;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Quality:" + Quality + ","
        + "Number:" + Number + ","
        + "}";
    }
}

}

