
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfWeaponAttribute : Luban.BeanBase
{
    public CfWeaponAttribute(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Atk = _buf.ReadFloat();
        CD = _buf.ReadFloat();
        Hp = _buf.ReadFloat();
        ReHp = _buf.ReadFloat();
        Rng = _buf.ReadFloat();
        ReShld = _buf.ReadFloat();
        CritRate = _buf.ReadFloat();
        CritDmg = _buf.ReadFloat();
    }

    public static CfWeaponAttribute DeserializeCfWeaponAttribute(ByteBuf _buf)
    {
        return new Battle.CfWeaponAttribute(_buf);
    }

    /// <summary>
    /// 属性id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Atk;
    /// <summary>
    /// 冷却时间(s)
    /// </summary>
    public readonly float CD;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 回血
    /// </summary>
    public readonly float ReHp;
    /// <summary>
    /// 射程
    /// </summary>
    public readonly float Rng;
    /// <summary>
    /// 回盾
    /// </summary>
    public readonly float ReShld;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CritRate;
    /// <summary>
    /// 暴击伤害
    /// </summary>
    public readonly float CritDmg;
   
    public const int __ID__ = 1287928135;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Atk:" + Atk + ","
        + "CD:" + CD + ","
        + "Hp:" + Hp + ","
        + "reHp:" + ReHp + ","
        + "Rng:" + Rng + ","
        + "reShld:" + ReShld + ","
        + "CritRate:" + CritRate + ","
        + "CritDmg:" + CritDmg + ","
        + "}";
    }
}

}

