
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfWeaponGrade : Luban.BeanBase
{
    public CfWeaponGrade(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["itemAttr"].IsNumber) { throw new SerializationException(); }  ItemAttr = _buf["itemAttr"]; }
        { if(!_buf["QualityID"].IsNumber) { throw new SerializationException(); }  QualityID = _buf["QualityID"]; }
        { if(!_buf["LvlUnlockDesc"].IsNumber) { throw new SerializationException(); }  LvlUnlockDesc = _buf["LvlUnlockDesc"]; }
        { if(!_buf["RlUnlockDesc"].IsNumber) { throw new SerializationException(); }  RlUnlockDesc = _buf["RlUnlockDesc"]; }
        { if(!_buf["RlID"].IsNumber) { throw new SerializationException(); }  RlID = _buf["RlID"]; }
        { var __json0 = _buf["MergeStuff"]; if(!__json0.IsArray) { throw new SerializationException(); } MergeStuff = new System.Collections.Generic.List<Battle.ItemStuff>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Battle.ItemStuff __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Battle.ItemStuff.DeserializeItemStuff(__e0);  }  MergeStuff.Add(__v0); }   }
        { if(!_buf["Power"].IsNumber) { throw new SerializationException(); }  Power = _buf["Power"]; }
    }

    public static CfWeaponGrade DeserializeCfWeaponGrade(JSONNode _buf)
    {
        return new Battle.CfWeaponGrade(_buf);
    }

    /// <summary>
    /// 道具等级ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具属性
    /// </summary>
    public readonly int ItemAttr;
    /// <summary>
    /// 品质图
    /// </summary>
    public readonly int QualityID;
    /// <summary>
    /// 等级解锁描述
    /// </summary>
    public readonly int LvlUnlockDesc;
    /// <summary>
    /// 肉鸽解锁技能点
    /// </summary>
    public readonly int RlUnlockDesc;
    /// <summary>
    /// 肉鸽技能ID
    /// </summary>
    public readonly int RlID;
    /// <summary>
    /// 升级材料
    /// </summary>
    public readonly System.Collections.Generic.List<Battle.ItemStuff> MergeStuff;
    /// <summary>
    /// 战力
    /// </summary>
    public readonly int Power;
   
    public const int __ID__ = 1059937282;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in MergeStuff) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemAttr:" + ItemAttr + ","
        + "QualityID:" + QualityID + ","
        + "LvlUnlockDesc:" + LvlUnlockDesc + ","
        + "RlUnlockDesc:" + RlUnlockDesc + ","
        + "RlID:" + RlID + ","
        + "MergeStuff:" + Luban.StringUtil.CollectionToString(MergeStuff) + ","
        + "Power:" + Power + ","
        + "}";
    }
}

}

