
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfWeaponPray : Luban.BeanBase
{
    public CfWeaponPray(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = (Weapon.PrayType)_buf.ReadInt();
        Quality = (Weapon.Quality)_buf.ReadInt();
        GoodsId = _buf.ReadInt();
        Prop = _buf.ReadInt();
    }

    public static CfWeaponPray DeserializeCfWeaponPray(ByteBuf _buf)
    {
        return new Battle.CfWeaponPray(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Weapon.PrayType Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Weapon.Quality Quality;
    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly int Prop;
   
    public const int __ID__ = 1142838319;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Quality:" + Quality + ","
        + "GoodsId:" + GoodsId + ","
        + "Prop:" + Prop + ","
        + "}";
    }
}

}

