
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public sealed partial class CfWeaponPrayEnsure : Luban.BeanBase
{
    public CfWeaponPrayEnsure(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = (Weapon.PrayType)_buf.ReadInt();
        Quality = (Weapon.Quality)_buf.ReadInt();
        Number = _buf.ReadInt();
    }

    public static CfWeaponPrayEnsure DeserializeCfWeaponPrayEnsure(ByteBuf _buf)
    {
        return new Battle.CfWeaponPrayEnsure(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Weapon.PrayType Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Weapon.Quality Quality;
    /// <summary>
    /// 保底次数
    /// </summary>
    public readonly int Number;
   
    public const int __ID__ = -212419251;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Quality:" + Quality + ","
        + "Number:" + Number + ","
        + "}";
    }
}

}

