
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CfWeaponPray : Luban.BeanBase
{
    public CfWeaponPray(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (Weapon.PrayType)_buf["Type"].AsInt; }
        { if(!_buf["Quality"].IsNumber) { throw new SerializationException(); }  Quality = (Weapon.Quality)_buf["Quality"].AsInt; }
        { if(!_buf["GoodsId"].IsNumber) { throw new SerializationException(); }  GoodsId = _buf["GoodsId"]; }
        { if(!_buf["Prop"].IsNumber) { throw new SerializationException(); }  Prop = _buf["Prop"]; }
    }

    public static CfWeaponPray DeserializeCfWeaponPray(JSONNode _buf)
    {
        return new Battle.CfWeaponPray(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly Weapon.PrayType Type;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Weapon.Quality Quality;
    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int GoodsId;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly int Prop;
   
    public const int __ID__ = 1142838319;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Quality:" + Quality + ","
        + "GoodsId:" + GoodsId + ","
        + "Prop:" + Prop + ","
        + "}";
    }
}

}

