
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 元素种类
    /// </summary>
    [System.Flags]
    public enum ElementType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 物理
        /// </summary>
        Physical = 1,
        /// <summary>
        /// 狂风
        /// </summary>
        Wind = 2,
        /// <summary>
        /// 雷电
        /// </summary>
        Thunder = 4,
        /// <summary>
        /// 神圣
        /// </summary>
        Holy = 8,
        /// <summary>
        /// 寒冰
        /// </summary>
        Ice = 16,
        /// <summary>
        /// 毒
        /// </summary>
        Poison = 32,
        /// <summary>
        /// 火焰
        /// </summary>
        Fire = 64,
    }

} 

