
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 物品类型
    /// </summary>
    [System.Flags]
    public enum ItemType
    {
        /// <summary>
        /// 背包
        /// </summary>
        Backpack = 1,
        /// <summary>
        /// 所有加血回血回盾类
        /// </summary>
        Armor = 2,
        /// <summary>
        /// 所有武器类
        /// </summary>
        Weapon = 4,
        /// <summary>
        /// 战斗银币
        /// </summary>
        GoldItem = 8,
    }

} 

