
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 品质类型
    /// </summary>
    public enum ItemQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        None = 0,
        /// <summary>
        /// 绿
        /// </summary>
        Green = 1,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 2,
        /// <summary>
        /// 金
        /// </summary>
        Golden = 3,
        /// <summary>
        /// 橙
        /// </summary>
        Orange = 4,
        /// <summary>
        /// 彩
        /// </summary>
        Colorful = 5,
    }

} 

