
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Battle
{ 
    /// <summary>
    /// 目标选择类型
    /// </summary>
    public enum TargetSelectType
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 随机目标
        /// </summary>
        Random = 1,
        /// <summary>
        /// 最近敌人
        /// </summary>
        Nearst = 2,
    }

} 

