
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBFeatureUnlock
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfFeatureUnlock> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfFeatureUnlock> _dataList;
    
    public TBFeatureUnlock(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfFeatureUnlock>();
        _dataList = new System.Collections.Generic.List<Battle.CfFeatureUnlock>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfFeatureUnlock _v;
            _v = Battle.CfFeatureUnlock.DeserializeCfFeatureUnlock(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FunctionId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfFeatureUnlock> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfFeatureUnlock> DataList => _dataList;

    public Battle.CfFeatureUnlock GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfFeatureUnlock Get(int key) => _dataMap[key];
    public Battle.CfFeatureUnlock this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

