
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TBGLConst
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.GLConst> _dataMap;
    private readonly System.Collections.Generic.List<Battle.GLConst> _dataList;
    
    public TBGLConst(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.GLConst>();
        _dataList = new System.Collections.Generic.List<Battle.GLConst>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.GLConst _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Battle.GLConst.DeserializeGLConst(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.PoisonDamage, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.GLConst> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.GLConst> DataList => _dataList;

    public Battle.GLConst GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.GLConst Get(int key) => _dataMap[key];
    public Battle.GLConst this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

