
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBMonster
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfMonster> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfMonster> _dataList;
    
    public TBMonster(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfMonster>();
        _dataList = new System.Collections.Generic.List<Battle.CfMonster>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfMonster _v;
            _v = Battle.CfMonster.DeserializeCfMonster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfMonster> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfMonster> DataList => _dataList;

    public Battle.CfMonster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfMonster Get(int key) => _dataMap[key];
    public Battle.CfMonster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

