
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBRogueSkill
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfRogueSkill> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfRogueSkill> _dataList;
    
    public TBRogueSkill(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfRogueSkill>();
        _dataList = new System.Collections.Generic.List<Battle.CfRogueSkill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfRogueSkill _v;
            _v = Battle.CfRogueSkill.DeserializeCfRogueSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfRogueSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfRogueSkill> DataList => _dataList;

    public Battle.CfRogueSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfRogueSkill Get(int key) => _dataMap[key];
    public Battle.CfRogueSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

