
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBShopDaily
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfShopDaily> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfShopDaily> _dataList;
    
    public TBShopDaily(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfShopDaily>();
        _dataList = new System.Collections.Generic.List<Battle.CfShopDaily>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfShopDaily _v;
            _v = Battle.CfShopDaily.DeserializeCfShopDaily(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GoodsId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfShopDaily> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfShopDaily> DataList => _dataList;

    public Battle.CfShopDaily GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfShopDaily Get(int key) => _dataMap[key];
    public Battle.CfShopDaily this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

