
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBTaskCheckin
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfTaskCheckin> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfTaskCheckin> _dataList;
    
    public TBTaskCheckin(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfTaskCheckin>();
        _dataList = new System.Collections.Generic.List<Battle.CfTaskCheckin>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfTaskCheckin _v;
            _v = Battle.CfTaskCheckin.DeserializeCfTaskCheckin(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfTaskCheckin> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfTaskCheckin> DataList => _dataList;

    public Battle.CfTaskCheckin GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfTaskCheckin Get(int key) => _dataMap[key];
    public Battle.CfTaskCheckin this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

