
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBTaskType
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfTaskType> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfTaskType> _dataList;
    
    public TBTaskType(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfTaskType>();
        _dataList = new System.Collections.Generic.List<Battle.CfTaskType>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfTaskType _v;
            _v = Battle.CfTaskType.DeserializeCfTaskType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfTaskType> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfTaskType> DataList => _dataList;

    public Battle.CfTaskType GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfTaskType Get(int key) => _dataMap[key];
    public Battle.CfTaskType this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

