
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Battle
{
public partial class TBTaskList
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CfTaskList> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CfTaskList> _dataList;
    
    public TBTaskList(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CfTaskList>();
        _dataList = new System.Collections.Generic.List<Battle.CfTaskList>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Battle.CfTaskList _v;
            _v = Battle.CfTaskList.DeserializeCfTaskList(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CfTaskList> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CfTaskList> DataList => _dataList;

    public Battle.CfTaskList GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Battle.CfTaskList Get(int key) => _dataMap[key];
    public Battle.CfTaskList this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

